# -----------------------------------------------
# dmz-proxy — ModSecurity WAF + Reverse Proxy
# Sits in DMZ, filters traffic before web server
# -----------------------------------------------

server {
    listen 80;
    server_name _;

    # ModSecurity WAF
    modsecurity on;
    modsecurity_rules_file /etc/nginx/modsecurity.conf;

    # Logging
    access_log /var/log/nginx/lab-access.log;
    error_log  /var/log/nginx/lab-error.log warn;

    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    server_tokens off;

    # PHP API — served locally (ModSec alerts)
    location ~ \.php$ {
        fastcgi_pass unix:/run/php/php8.4-fpm.sock;
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
        include fastcgi_params;
    }

    # Reverse Proxy → internal web server
    location / {
        proxy_pass http://10.0.2.10:80/;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_connect_timeout 10s;
        proxy_read_timeout    30s;
    }
}

# -----------------------------------------------
# Lab Proxy — port 8080 (transparent HTTP proxy)
# Used for traffic analysis and malware testing
# -----------------------------------------------

server {
    listen 8080;
    server_name _;

    modsecurity on;
    modsecurity_rules_file /etc/nginx/modsecurity.conf;

    access_log /var/log/nginx/lab-access.log;
    error_log  /var/log/nginx/lab-error.log warn;

    location / {
        proxy_pass http://$http_host$request_uri;
        proxy_set_header Host       $http_host;
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_connect_timeout 10s;
        proxy_read_timeout    30s;
        resolver 9.9.9.9;
    }
}
